[build-system]
requires = ["hatchling",
            "browser-cookie3",
            "beautifulsoup4",
            "numpy",
            "pandas",
            "requests",
            "selenium",
            "webdriver-manager"]
build-backend = "hatchling.build"

[project]
name = "pyktok"
version = "0.0.10"
authors = [
  { name="Deen Freelon", email="dfreelon@gmail.com"},
]
description = "A package for collecting TikTok videos and metadata."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/dfreelon/pyktok"
